create table public.conversations (
  id bigint generated by default as identity not null,
  title text null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint conversations_pkey primary key (id)
) TABLESPACE pg_default;

create table public.messages (
  id bigint generated by default as identity not null,
  conversation_id bigint not null,
  role text not null,
  content text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint messages_pkey primary key (id),
  constraint messages_conversation_id_fkey foreign KEY (conversation_id) references conversations (id),
  constraint messages_role_check check (
    (
      role = any (
        array['user'::text, 'assistant'::text, 'system'::text]
      )
    )
  )
) TABLESPACE pg_default;